name: Testing Workflow Dispatch
on: 
  workflow_dispatch:
    inputs:
      name: 
        description: Name of the user
        required: true
jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World!
        run: "echo \"Hello ${{ inputs.name }}\""

      - name: "Another echo"
        run: "echo \"Hi!\""

